### PR TITLE
Do not raise error: "Unknown cookie parameter 'samesite'"

### PR DESCRIPTION
**Pull request by beyondcompute**
This might potentially break some other projects that use this. It’s not too likely probably though.

This actually has some attempts in the origin repository PRs: https://github.com/dwaite/cookiejar/pulls?q=is%3Apr

### CODE REVIEW

**Review by edimossilva — APPROVED** [review]
SGTM and safe

**Comment by beyondcompute** [comment]
No, not yet.

**Comment by beyondcompute** [comment]
And it’s not boolean.

**Comment by beyondcompute** [comment]
@edimossilva Ok, it was added here: https://github.com/dwaite/cookiejar/pull/29
So we could just “re-fetch the origin” to our fork. That might be a bit more dangerous but also it’s a good idea to stay up-to-date.

**Pull request closed without merging**
